apiVersion: v1
kind: Service
metadata:
  labels:
    app: mathApp
  name: mathApp
spec:
  ports:
  - name: 80-5000
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: mathApp
  type: LoadBalancer
