apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: math-app
  name: math-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: math-app
  strategy: {}
  template:
    metadata:
      labels:
        app: math-app
    spec:
      containers:
      - image: villavelle101/maths:31
        name: test-app
        resources: {}
