apiVersion: v1
kind: Service
metadata:
  labels:
    app: math-app
  name: math-app
spec:
  ports:
  - name: 80-5000
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: math-app
  type: LoadBalancer
